server:
  port: 8009
grpc:
  port: 6565

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name : org.h2.Driver
    username : sa
    password : admin
    database-platform : org.hibernate.dialect.H2Dialect
    ddl-auto : update
  jpa:
    show-sql : true